export interface PlayerEntry {
  slug: string;
  wikiSlug: string;
  gender?: 'H' | 'F';
}

export const PLAYERS_TO_SCRAPE: PlayerEntry[] = [
  // ── Men's singles — legends ────────────────────────────────
  { slug: 'lin-dan',          wikiSlug: 'Lin_Dan',          gender: 'H' },
  { slug: 'lee-chong-wei',    wikiSlug: 'Lee_Chong_Wei',    gender: 'H' },
  { slug: 'taufik-hidayat',   wikiSlug: 'Taufik_Hidayat',   gender: 'H' },
  { slug: 'peter-gade',       wikiSlug: 'Peter_Gade',       gender: 'H' },
  { slug: 'chen-long',        wikiSlug: 'Chen_Long',        gender: 'H' },
  { slug: 'kento-momota',     wikiSlug: 'Kento_Momota',     gender: 'H' },
  { slug: 'rudy-hartono',     wikiSlug: 'Rudy_Hartono',     gender: 'H' },
  { slug: 'morten-frost',     wikiSlug: 'Morten_Frost',     gender: 'H' },
  { slug: 'bao-chunlai',      wikiSlug: 'Bao_Chunlai',      gender: 'H' },
  { slug: 'kenichi-tago',     wikiSlug: 'Kenichi_Tago',     gender: 'H' },
  { slug: 'sony-dwi-kuncoro', wikiSlug: 'Sony_Dwi_Kuncoro', gender: 'H' },

  // ── Men's singles — active ─────────────────────────────────
  { slug: 'viktor-axelsen',     wikiSlug: 'Viktor_Axelsen',            gender: 'H' },
  { slug: 'shi-yuqi',           wikiSlug: 'Shi_Yuqi',                  gender: 'H' },
  { slug: 'anders-antonsen',    wikiSlug: 'Anders_Antonsen',           gender: 'H' },
  { slug: 'kunlavut-vitidsarn', wikiSlug: 'Kunlavut_Vitidsarn',        gender: 'H' },
  { slug: 'jonatan-christie',   wikiSlug: 'Jonatan_Christie',          gender: 'H' },
  { slug: 'anthony-ginting',    wikiSlug: 'Anthony_Sinisuka_Ginting',  gender: 'H' },
  { slug: 'chou-tien-chen',     wikiSlug: 'Chou_Tien-chen',            gender: 'H' },
  { slug: 'lakshya-sen',        wikiSlug: 'Lakshya_Sen',               gender: 'H' },
  { slug: 'loh-kean-yew',       wikiSlug: 'Loh_Kean_Yew',              gender: 'H' },
  { slug: 'lee-zii-jia',        wikiSlug: 'Lee_Zii_Jia',               gender: 'H' },
  { slug: 'kodai-naraoka',      wikiSlug: 'Kodai_Naraoka',             gender: 'H' },
  { slug: 'alex-lanier',        wikiSlug: 'Alex_Lanier',               gender: 'H' },
  { slug: 'christo-popov',      wikiSlug: 'Christo_Popov',             gender: 'H' },
  { slug: 'srikanth-kidambi',   wikiSlug: 'Kidambi_Srikanth',          gender: 'H' },
  { slug: 'hs-prannoy',         wikiSlug: 'Prannoy_H._S.',             gender: 'H' },
  { slug: 'brice-leverdez',     wikiSlug: 'Brice_Leverdez',            gender: 'H' },
  { slug: 'ng-ka-long',         wikiSlug: 'Ng_Ka_Long',                gender: 'H' },
  { slug: 'tommy-sugiarto',     wikiSlug: 'Tommy_Sugiarto',            gender: 'H' },
  { slug: 'hans-vittinghus',    wikiSlug: 'Hans-Kristian_Vittinghus', gender: 'H' },

  // ── Women's singles — legends ──────────────────────────────
  { slug: 'susi-susanti',       wikiSlug: 'Susi_Susanti',       gender: 'F' },
  { slug: 'zhang-ning',         wikiSlug: 'Zhang_Ning',         gender: 'F' },
  { slug: 'wang-yihan',         wikiSlug: 'Wang_Yihan',         gender: 'F' },
  { slug: 'li-xuerui',          wikiSlug: 'Li_Xuerui',          gender: 'F' },
  { slug: 'saina-nehwal',       wikiSlug: 'Saina_Nehwal',       gender: 'F' },
  { slug: 'nozomi-okuhara',     wikiSlug: 'Nozomi_Okuhara',     gender: 'F' },
  { slug: 'tai-tzu-ying',       wikiSlug: 'Tai_Tzu-ying',       gender: 'F' },
  { slug: 'ratchanok-intanon',  wikiSlug: 'Ratchanok_Intanon',  gender: 'F' },
  { slug: 'xie-xingfang',       wikiSlug: 'Xie_Xingfang',       gender: 'F' },
  { slug: 'wang-shixian',       wikiSlug: 'Wang_Shixian',       gender: 'F' },
  { slug: 'wang-xin',           wikiSlug: 'Wang_Xin_(badminton)', gender: 'F' },

  // ── Women's singles — active ───────────────────────────────
  { slug: 'an-seyoung',         wikiSlug: 'An_Se-young',        gender: 'F' },
  { slug: 'carolina-marin',     wikiSlug: 'Carolina_Mar%C3%ADn', gender: 'F' },
  { slug: 'pv-sindhu',          wikiSlug: 'P._V._Sindhu',       gender: 'F' },
  { slug: 'chen-yufei',         wikiSlug: 'Chen_Yufei',         gender: 'F' },
  { slug: 'akane-yamaguchi',    wikiSlug: 'Akane_Yamaguchi',    gender: 'F' },
  { slug: 'he-bingjiao',        wikiSlug: 'He_Bingjiao',        gender: 'F' },
  { slug: 'pornpawee-chochuwong', wikiSlug: 'Pornpawee_Chochuwong', gender: 'F' },
  { slug: 'gregoria-tunjung',   wikiSlug: 'Gregoria_Mariska_Tunjung', gender: 'F' },
  { slug: 'sung-ji-hyun',       wikiSlug: 'Sung_Ji-hyun',       gender: 'F' },
  { slug: 'beiwen-zhang',       wikiSlug: 'Beiwen_Zhang',       gender: 'F' },
  { slug: 'mia-blichfeldt',     wikiSlug: 'Mia_Blichfeldt',     gender: 'F' },
  { slug: 'wang-zhiyi',         wikiSlug: 'Wang_Zhiyi',         gender: 'F' },
  { slug: 'aya-ohori',          wikiSlug: 'Aya_Ohori',          gender: 'F' },

  // ── Men's doubles ──────────────────────────────────────────
  { slug: 'mohammad-ahsan',     wikiSlug: 'Mohammad_Ahsan',     gender: 'H' },
  { slug: 'hendra-setiawan',    wikiSlug: 'Hendra_Setiawan',    gender: 'H' },
  { slug: 'marcus-gideon',      wikiSlug: 'Marcus_Fernaldi_Gideon', gender: 'H' },
  { slug: 'kevin-sanjaya',      wikiSlug: 'Kevin_Sanjaya_Sukamuljo', gender: 'H' },
  { slug: 'lee-yong-dae',       wikiSlug: 'Lee_Yong-dae',       gender: 'H' },
  { slug: 'cai-yun',            wikiSlug: 'Cai_Yun',            gender: 'H' },
  { slug: 'fu-haifeng',         wikiSlug: 'Fu_Haifeng',         gender: 'H' },
  { slug: 'mathias-boe',        wikiSlug: 'Mathias_Boe',        gender: 'H' },
  { slug: 'carsten-mogensen',   wikiSlug: 'Carsten_Mogensen',   gender: 'H' },
  { slug: 'hiroyuki-endo',      wikiSlug: 'Hiroyuki_Endo',      gender: 'H' },
  { slug: 'takeshi-kamura',     wikiSlug: 'Takeshi_Kamura',     gender: 'H' },
  { slug: 'keigo-sonoda',       wikiSlug: 'Keigo_Sonoda',       gender: 'H' },
  { slug: 'aaron-chia',         wikiSlug: 'Aaron_Chia',         gender: 'H' },
  { slug: 'soh-wooi-yik',       wikiSlug: 'Soh_Wooi_Yik',       gender: 'H' },
  { slug: 'liu-yuchen',         wikiSlug: 'Liu_Yuchen',         gender: 'H' },
  { slug: 'li-junhui',          wikiSlug: 'Li_Junhui',          gender: 'H' },

  // ── Women's doubles ────────────────────────────────────────
  { slug: 'gao-ling',           wikiSlug: 'Gao_Ling',           gender: 'F' },
  { slug: 'matsumoto-mayu',     wikiSlug: 'Mayu_Matsumoto',     gender: 'F' },
  { slug: 'chen-qingchen',      wikiSlug: 'Chen_Qingchen',      gender: 'F' },
  { slug: 'yu-yang',            wikiSlug: 'Yu_Yang_(badminton)', gender: 'F' },
  { slug: 'wang-xiaoli',        wikiSlug: 'Wang_Xiaoli',        gender: 'F' },
  { slug: 'misaki-matsutomo',   wikiSlug: 'Misaki_Matsutomo',   gender: 'F' },
  { slug: 'ayaka-takahashi',    wikiSlug: 'Ayaka_Takahashi',    gender: 'F' },
  { slug: 'greysia-polii',      wikiSlug: 'Greysia_Polii',      gender: 'F' },
  { slug: 'apriyani-rahayu',    wikiSlug: 'Apriyani_Rahayu',    gender: 'F' },
  { slug: 'lee-so-hee',         wikiSlug: 'Lee_So-hee',         gender: 'F' },
  { slug: 'jia-yifan',          wikiSlug: 'Jia_Yifan',          gender: 'F' },
  { slug: 'yuki-fukushima',     wikiSlug: 'Yuki_Fukushima',     gender: 'F' },
  { slug: 'sayaka-hirota',      wikiSlug: 'Sayaka_Hirota',      gender: 'F' },

  // ── Mixed doubles ──────────────────────────────────────────
  { slug: 'zheng-siwei',        wikiSlug: 'Zheng_Siwei',        gender: 'H' },
  { slug: 'huang-yaqiong',      wikiSlug: 'Huang_Yaqiong',      gender: 'F' },
  { slug: 'tontowi-ahmad',      wikiSlug: 'Tontowi_Ahmad',      gender: 'H' },
  { slug: 'liliyana-natsir',    wikiSlug: 'Liliyana_Natsir',    gender: 'F' },
  { slug: 'dechapol-puavaranukroh', wikiSlug: 'Dechapol_Puavaranukroh', gender: 'H' },
  { slug: 'kim-dong-moon',      wikiSlug: 'Kim_Dong-moon',      gender: 'H' },
  { slug: 'yuta-watanabe',      wikiSlug: 'Yuta_Watanabe_(badminton)', gender: 'H' },
  { slug: 'arisa-higashino',    wikiSlug: 'Arisa_Higashino',    gender: 'F' },
  { slug: 'wang-yilyu',         wikiSlug: 'Wang_Yil%C3%BC',     gender: 'H' },
  { slug: 'huang-dongping',     wikiSlug: 'Huang_Dongping',     gender: 'F' },
  { slug: 'praveen-jordan',     wikiSlug: 'Praveen_Jordan',     gender: 'H' },
  { slug: 'melati-oktavianti',  wikiSlug: 'Melati_Daeva_Oktavianti', gender: 'F' },
  { slug: 'tang-chun-man',      wikiSlug: 'Tang_Chun_Man',      gender: 'H' },
  { slug: 'tse-ying-suet',      wikiSlug: 'Tse_Ying_Suet',      gender: 'F' },
  { slug: 'goh-soon-huat',      wikiSlug: 'Goh_Soon_Huat',      gender: 'H' },
  { slug: 'shevon-lai',         wikiSlug: 'Lai_Pei_Jing',       gender: 'F' },
  { slug: 'marcus-ellis',       wikiSlug: 'Marcus_Ellis',       gender: 'H' },
  { slug: 'lauren-smith',       wikiSlug: 'Lauren_Smith_(badminton)', gender: 'F' },
  { slug: 'chen-tang-jie',      wikiSlug: 'Chen_Tang_Jie',      gender: 'H' },
  { slug: 'toh-ee-wei',         wikiSlug: 'Toh_Ee_Wei',         gender: 'F' },

  // ── French players (mode FR) ───────────────────────────────
  { slug: 'toma-popov',         wikiSlug: 'Toma_Junior_Popov',  gender: 'H' },
  { slug: 'pi-hongyan',         wikiSlug: 'Pi_Hongyan',         gender: 'F' },
  { slug: 'thom-gicquel',       wikiSlug: 'Thom_Gicquel',       gender: 'H' },
  { slug: 'delphine-delrue',    wikiSlug: 'Delphine_Delrue',    gender: 'F' },
  { slug: 'anne-tran',          wikiSlug: 'Anne_Tran',          gender: 'F' },
  { slug: 'bastian-kersaudy',   wikiSlug: 'Bastian_Kersaudy',   gender: 'H' },
  { slug: 'ronan-labar',        wikiSlug: 'Ronan_Labar',        gender: 'H' },
  { slug: 'lucas-corvee',       wikiSlug: 'Lucas_Corv%C3%A9e',  gender: 'H' },
  { slug: 'william-villeger',   wikiSlug: 'William_Villeger',   gender: 'H' },
  { slug: 'margot-lambert',     wikiSlug: 'Margot_Lambert',     gender: 'F' },
  // French men — extra
  { slug: 'mihail-popov',       wikiSlug: 'Mihail_Popov',           gender: 'H' },
  { slug: 'arnaud-merkle',      wikiSlug: 'Arnaud_Merkl%C3%A9',     gender: 'H' },
  { slug: 'maxime-mora',        wikiSlug: 'Maxime_Mora',            gender: 'H' },
  { slug: 'leo-rossi',          wikiSlug: 'L%C3%A9o_Rossi',         gender: 'H' },
  { slug: 'thomas-rouxel',      wikiSlug: 'Thomas_Rouxel',          gender: 'H' },
  { slug: 'vanmael-heriau',     wikiSlug: 'Vanmael_H%C3%A9riau',    gender: 'H' },
  { slug: 'fabien-delrue',      wikiSlug: 'Fabien_Delrue',          gender: 'H' },
  { slug: 'julien-maio',        wikiSlug: 'Julien_Maio',            gender: 'H' },
  { slug: 'lucas-claerbout',    wikiSlug: 'Lucas_Claerbout',        gender: 'H' },
  // meril-loquette retiré : joue principalement en para-badminton, ranking non comparable au BWF mondial
  // French women — extra
  { slug: 'leonice-huet',       wikiSlug: 'L%C3%A9onice_Huet',      gender: 'F' },
  { slug: 'marie-batomene',     wikiSlug: 'Marie_Batomene',         gender: 'F' },
  { slug: 'emilie-lefel',       wikiSlug: '%C3%89milie_Lefel',      gender: 'F' },
  { slug: 'vimala-heriau',      wikiSlug: 'Vimala_H%C3%A9riau',     gender: 'F' },
  { slug: 'lea-palermo',        wikiSlug: 'L%C3%A9a_Palermo',       gender: 'F' },
  { slug: 'sashina-vignes-waran', wikiSlug: 'Sashina_Vignes_Waran', gender: 'F' },
  { slug: 'audrey-mittelheisser', wikiSlug: 'Audrey_Mittelheisser', gender: 'F' },
];
